<?php
/**
 * Adds the default ACF fields included with our Theme
 *
 * @package gotheme
 * @author goBRANDgo
 * 
 */

if ( function_exists( 'register_field_group' ) ) {
	
	register_field_group(array(
		'id' => 'acf_brand-guidelines',
		'title' => 'Brand Guidelines',
		'fields' => array(
			array(
				'key' => 'field_5552129a0b675',
				'label' => 'Page Header Text',
				'name' => 'page_header_text',
				'type' => 'textarea',
				'default_value' => 'Official [COMPANY NAME] Logo is to be only used within the below restrictions.
	If any branding questions arise please <a href="/contact-us">contact us</a>.',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
			array(
				'key' => 'field_555213150b676',
				'label' => 'Logo Rules',
				'name' => 'logo_rules',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
			array(
				'key' => 'field_555213360b677',
				'label' => 'Font Rules',
				'name' => 'font_rules',
				'type' => 'textarea',
				'default_value' => 'The main brand fonts are ["PRIMARY FONT"] and ["SECONDARY FONT"]. If these fonts are not available, ["FALLBACK FONT"] is an acceptable serif alternative.',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
			array(
				'key' => 'field_555213f80b678',
				'label' => 'The Logos List',
				'name' => 'the_logos_list',
				'type' => 'repeater',
				'sub_fields' => array(
					array(
						'key' => 'field_555214260b679',
						'label' => 'Logo Type',
						'name' => 'logo_type',
						'type' => 'text',
						'instructions' => 'ex: Full Color',
						'required' => 1,
						'column_width' => 10,
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array(
						'key' => 'field_555214860b67a',
						'label' => 'unzipped logo',
						'name' => 'unzipped_logo',
						'type' => 'image',
						'instructions' => 'A png or jpg to display on the page',
						'column_width' => 30,
						'save_format' => 'url',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array(
						'key' => 'field_555214b60b67b',
						'label' => 'Logos to Download',
						'name' => 'logos_to_download',
						'type' => 'repeater',
						'instructions' => 'The zipped Logos',
						'column_width' => 60,
						'sub_fields' => array(
							array(
								'key' => 'field_555215000b67c',
								'label' => 'The Logo',
								'name' => 'the_logo',
								'type' => 'file',
								'column_width' => '',
								'save_format' => 'url',
								'library' => 'all',
							),
							array(
								'key' => 'field_5552151c0b67d',
								'label' => 'File Type',
								'name' => 'file_type',
								'type' => 'text',
								'instructions' => 'ex: JPG',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
						'row_min' => '',
						'row_limit' => '',
						'layout' => 'table',
						'button_label' => 'Add Downloadable Logo',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Logo Type',
			),
			array(
				'key' => 'field_55521829aa436',
				'label' => 'Color Rules',
				'name' => 'color_rules',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
			array(
				'key' => 'field_5552187eaa438',
				'label' => 'Has Multiple Primary Colors',
				'name' => 'has_multiple_primary_colors',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
			),
			array(
				'key' => 'field_555218b3aa439',
				'label' => 'Primary Color Hex',
				'name' => 'pc_hex',
				'type' => 'text',
				'conditional_logic' => array(
					'status' => 1,
					'rules' => array(
						array(
							'field' => 'field_5552187eaa438',
							'operator' => '!=',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array(
				'key' => 'field_555218efaa43b',
				'label' => 'Primary Color CMYK',
				'name' => 'pc_cmyk',
				'type' => 'text',
				'conditional_logic' => array(
					'status' => 1,
					'rules' => array(
						array(
							'field' => 'field_5552187eaa438',
							'operator' => '!=',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5552190faa43c',
				'label' => 'Primary Color RGB',
				'name' => 'pc_rgb',
				'type' => 'text',
				'conditional_logic' => array(
					'status' => 1,
					'rules' => array(
						array(
							'field' => 'field_5552187eaa438',
							'operator' => '!=',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array(
				'key' => 'field_55521922aa43d',
				'label' => 'Primary Color PMS',
				'name' => 'pc_pms',
				'type' => 'text',
				'conditional_logic' => array(
					'status' => 1,
					'rules' => array(
						array(
							'field' => 'field_5552187eaa438',
							'operator' => '!=',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array(
				'key' => 'field_555219383b273',
				'label' => 'Primary Colors',
				'name' => 'primary_colors_rep',
				'type' => 'repeater',
				'conditional_logic' => array(
					'status' => 1,
					'rules' => array(
						array(
							'field' => 'field_5552187eaa438',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'sub_fields' => array(
					array(
						'key' => 'field_555219593b274',
						'label' => 'Hex',
						'name' => 'hex',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array(
						'key' => 'field_555219613b275',
						'label' => 'CMYK',
						'name' => 'cmyk',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array(
						'key' => 'field_555219663b276',
						'label' => 'RGB',
						'name' => 'rgb',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5552196c3b277',
						'label' => 'PMS',
						'name' => 'pms',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Primary Color',
			),
			array(
				'key' => 'field_5552197cbd372',
				'label' => 'Secondary Colors List',
				'name' => 'secondary_colors_list',
				'type' => 'repeater',
				'sub_fields' => array(
					array(
						'key' => 'field_555219a2bd373',
						'label' => 'Hex',
						'name' => 'hexs',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array(
						'key' => 'field_555219a9bd374',
						'label' => 'CMYK',
						'name' => 'cmyks',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array(
						'key' => 'field_555219aebd375',
						'label' => 'RGB',
						'name' => 'rgbs',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array(
						'key' => 'field_555219c5bd376',
						'label' => 'PMS',
						'name' => 'pmss',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Secondary Color',
			),
			array(
				'key' => 'field_555219e4b5f8e',
				'label' => 'Brand Guidelines',
				'name' => 'brand_guidelines',
				'type' => 'file',
				'instructions' => 'Optional. Downloadable Brand Guidelines.',
				'save_format' => 'url',
				'library' => 'all',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'inc/template-brand-logo.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array(
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array(
				0 => 'the_content',
			),
		),
		'menu_order' => 0,
	));

}
?>
